### PR TITLE
fixed TS error

### PR DESCRIPTION
**Pull request by sahandfarahani**

### CODE REVIEW

**Comment by sahandfarahani** [comment]
@ralph-dev  this should fix the TS error

**Comment by sahandfarahani** [comment]
> Run `tsc` to make sure before you merge

@ralph-dev 
I get this:

```
$ npm run tsc
npm ERR! missing script: tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sahand\AppData\Roaming\npm-cache\_logs\2020-07-16T15_42_31_023Z-debug.log

```

**Comment by ralph-dev** [comment]
Okay then just merge for now but google this issue becuase you should have tsc to check for type issues

**Comment by ralph-dev** [comment]
Try npm install -g typescript

**Comment by sahandfarahani** [comment]
> Try npm install -g typescript

I just put  "scripts": {
    "tsc": "tsc"
  },
in package

and now its
```

$ npm run tsc

> readme-dirs@0.1.0 tsc E:\tocommit\withnpm
> tsc
```

**Pull request merged**
