### PR TITLE
Update undoDeletions.ts

### PR DESCRIPTION
**Pull request by Manpreet-Bhatti**
Fixed an issue where sometimes undoing a deletion would undo the last two instead of the last deletion -- was not behaving the way it should be.

### CODE REVIEW

**Comment by Manpreet-Bhatti** [comment]
Had a looping, recursion, and reassignment problem which I believe I fixed.

**Comment by Manpreet-Bhatti** [comment]
> LGTM, Have you tested this? Make a Test that calls Delete twice on a Tree then Calls undo once then compare tree?

Yup! This has been tested using the same tests we had before -- will do as you said as well, though, to double check!

**Comment by ralph-dev** [comment]
@Manpreet-Bhatti But the tests before didn't catch the issue so maybe add more coverage for more edge cases :) then merge

**Comment by sahandfarahani** [comment]
@Manpreet-Bhatti could you solve the Conflict Error to merge the PR?

**Comment by Manpreet-Bhatti** [comment]
> @Manpreet-Bhatti could you solve the Conflict Error to merge the PR?

Yup, going to add a few more tests, and then merge

**Pull request merged**
